import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import StyleProvider from "@/components/generals/Styleprovider";
import HomeLayout from "@/components/generals/Homelayout";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import Menu from "@/components/sideMenu/Menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider options={{ key: "css" }}>
          <StyleProvider>
            <Navbar />
            <Menu />
            {children}
          </StyleProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
